name: crypto_wallet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    cloud_firestore: ^2.4.0
    cupertino_icons: ^1.0.2
    firebase_auth: ^3.0.1
    firebase_core: ^1.4.0
    get: 4.2.4
    http: ^0.13.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    lints: 1.0.1

flutter:
    uses-material-design: true
